PHONES_MARKETE/Controllers/UsersController.cs
using Bl;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PHONES_MARKETE.Areas.admin.Controllers;
using PHONES_MARKETE.Models;
using System.Collections.Generic;

namespace PHONES_MARKETE.Controllers
{
    public class UsersController : Controller
    {

        UserManager<MyApplicationUser> _userManager;
        SignInManager<MyApplicationUser> _signInManager;
        public UsersController(UserManager<MyApplicationUser> userManager,
            SignInManager<MyApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Login(string returnUrl)
        {
            UserModelUrl model = new UserModelUrl()
            {
                ReturnUrl = returnUrl
            };
            return View(model);
        }

        public async Task<IActionResult> LoginOut()
        {
            await _signInManager.SignOutAsync();
            return Redirect("~/");
        }

        public IActionResult Register()
        {
            return View(new UserModel());
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserModel model)
        {
            if (!ModelState.IsValid)
                return View("Register", model);

            var user = new MyApplicationUser()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                UserName = model.Email,
                 PhoneNumber = model.PhoneNumber,
                City = model.City
            };
            try
            {
                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    // If the user is signed in and in the Admin role, then it is
                    // the Admin user that is creating a new user. So redirect the
                    // Admin user to ListRoles action
                    if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        var User = await _userManager.FindByEmailAsync(user.Email);
                        await _userManager.AddToRoleAsync(User, "Customer");

                        return RedirectToAction("List","AllUsers", new { area = "admin" });
                      
                    }

                    var loginResult = await _signInManager.PasswordSignInAsync(user, model.Password, true, true);
                    var myUser = await _userManager.FindByEmailAsync(user.Email);
                    await _userManager.AddToRoleAsync(myUser, "Customer");
                    if (loginResult.Succeeded)
                        return RedirectToAction("Index", "Home");
                }
                else
                {

                }
            }
            catch (Exception ex)
            {

            }
            return View(new UserModel());
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserModelUrl model)
        {
            MyApplicationUser user = new MyApplicationUser()
            {
                Email = model.Email,
                UserName = model.Email
            };
            try
            {
                var loginResult = await _signInManager.PasswordSignInAsync(user.Email, model.Password, true, true);
                if (loginResult.Succeeded)
                {
                    if (string.IsNullOrEmpty(model.ReturnUrl))
                        return Redirect("~/");
                    else
                        return Redirect(model.ReturnUrl);
                }
            }
            catch (Exception ex)
            {

            }
            return View(new UserModel());
        }
        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }


    }
}

PHONES_MARKETE/Views/Users/AccessDenied.cshtml
<section class="cart-section section-b-space">
    <div class="container">
       
        <div class="row cart-buttons">
            <div class="banner-contain">
              <h3>
                    U Are Not Authorizer
              </h3>
              <div>

              </div>

                <div class="col-6"><a href="/Home/Index" class="btn btn-solid">continue shopping</a></div>

            </div>
            
        </div>
    </div>
</section>

PHONES_MARKETE/Views/Users/Login.cshtml
@model UserModelUrl


<!-- breadcrumb start -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="page-title">
                    <h2>customer's login</h2>
                </div>
            </div>
            <div class="col-sm-6">
                <nav aria-label="breadcrumb" class="theme-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        <li class="breadcrumb-item active">login</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb End -->
<!--section start-->
<section class="login-page section-b-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h3>Login</h3>
                <div class="theme-card">
                    <form method="post"
                          asp-controller="Users" asp-action="Login"
                          class="theme-form">
                        <input asp-for="ReturnUrl" type="hidden" />
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input asp-for="Email"
                                   type="text" class="form-control" id="email" placeholder="Email" required="">
                        </div>
                        <div class="form-group">
                            <label for="review">Password</label>
                            <input asp-for="Password"
                                   type="password" class="form-control" id="review"
                                   placeholder="Enter your password" required="">
                        </div>
                        <button type="submit" class="btn btn-solid">Login</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-6 right-login">
                <h3>New Customer</h3>
                <div class="theme-card authentication-right">
                    <h6 class="title-font">Create A Account</h6>
                    <p>
                        Sign up for a free account at our store. Registration is quick and easy. It allows you to be
                        able to order from our shop. To start shopping click register.
                    </p>
                    <a href="/Users/Register"
                       class="btn btn-solid">Create an Account</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Section ends-->

PHONES_MARKETE/Views/Users/Register.cshtml
@model UserModel

<!-- breadcrumb start -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="page-title">
                    <h2>create account</h2>
                </div>
            </div>
            <div class="col-sm-6">
                <nav aria-label="breadcrumb" class="theme-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">create account</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb End -->
<!--section start-->
<section class="register-page section-b-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>create account</h3>
                <div class="theme-card">
                    <form class="theme-form" method="post"
                          asp-controller="Users" asp-action="Register">
                        <div class="form-row">
                            <div asp-validation-summary="All">
                            </div>
                            <div class="col-md-6">
                                <label for="email">First Name</label>
                                <input asp-for="FirstName"
                                       type="text" class="form-control" id="fname" placeholder="First Name"
                                       required="">
                                <span asp-validation-for="FirstName"></span>
                            </div>
                            <div class="col-md-6">
                                <label for="review">Last Name</label>
                                <input asp-for="LastName"
                                       type="text" class="form-control" id="lname" placeholder="Last Name"
                                       required="">
                                <span asp-validation-for="LastName"></span>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="email">email</label>
                                <input asp-for="Email"
                                       type="text" class="form-control" id="email" placeholder="Email" required="">
                                <span asp-validation-for="Email"></span>
                            </div>
                            <div class="col-md-6">
                                <label for="review">Password</label>
                                <input asp-for="Password"
                                       type="password" class="form-control" id="review"
                                       placeholder="Enter your password" required="">
                                <span asp-validation-for="Password"></span>
                            </div>
                            <div class="col-md-6">
                                <label for="review">City</label>
                                <input asp-for="City"
                                       type="text" class="form-control" id="review"
                                       placeholder="Enter your City" required="">
                                <span asp-validation-for="City"></span>
                            </div>
                            <div class="col-md-6">
                                <label for="review">Phone Number</label>
                                <input asp-for="PhoneNumber"
                                       type="text" class="form-control" id="review"
                                       placeholder="Enter your Number" required="">
                                <span asp-validation-for="PhoneNumber"></span>
                            </div>
                            <button type="submit" class="btn btn-solid">create Account</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Section ends-->